### PR TITLE
feat: replace symlink with simple shell wrapper

### PR DESCRIPTION
**Pull request by Chumper**
Replaces the symlink for tools with a simple shell wrapper

### CODE REVIEW

**Comment by Chumper** [comment]
Closes #338

**Review by viceice — COMMENTED** [review]
Node tests are failing. 🤔

**Comment by Chumper** [comment]
yes, but i don't understand why... I need to dig deeper to understand the problem

**Comment by Chumper** [comment]
I am not able to find the error. I suspect due to the shell script, paths have been changed but even a diff of the working and failing run does not bring me closer to a solution.

**Comment by Chumper** [comment]
Apparently with `ln` npm gets installed in `/home/user/npm/8.0.0`, with the shell script in `/home/user/.npm-global/bin/npm`

**Comment by viceice** [comment]
We should not change `link_wrapper`, instead we should move all tools to `shell_wrapper` and v2 tools.

**Comment by florianklumb** [comment]
Any verdict on when this will be deployed (into Docker image)?

**Comment by Chumper** [comment]
We opted for refactoring all tool afaik instead of replacing this for all tools at once.

**Comment by viceice** [comment]
@florianklumb So you have issues? PLease open a discussion, so we can checkout your usecase. And then we can open an issue if there is a feature request or bug

**Pull request closed without merging**
