### PR TITLE
feat: add flutter

### LINKED ISSUE #200: add flutter tool
- [x] blocked by https://github.com/renovatebot/renovate/issues/12820
- [ ] helps for renovatebot/renovate#6049

### PR DESCRIPTION
**Pull request by viceice**
- required for renovatebot/renovate#6049
- closes #200
- blocked by https://github.com/renovatebot/renovate/issues/12820

### CODE REVIEW

**Comment by jld3103** [comment]
Hey what is up with this PR? I created https://github.com/renovatebot/renovate/pull/11132 which depends on this in theory.

**Comment by BjoernPetersen** [comment]
What's missing for this pull request?

**Comment by viceice** [comment]
Deconflicting and time 😉

**Comment by BjoernPetersen** [comment]
I resolved the conflicts and fixed linting errors in a fork of mine: https://github.com/BjoernPetersen/buildpack/tree/feat/flutter

Seems like I'd need to either heavily adjust the CI config or create a competing PR here to test the build/lang job. Would you be open to pulling the changes from my fork into this PR?

**Comment by viceice** [comment]
Feel free to open a pr and target my branch

**Comment by Nirajn2311** [comment]
Hi, any update on this?

**Comment by jld3103** [comment]
Now that this is merged, can I use it for https://github.com/renovatebot/renovate/pull/11132 ? The PR has been locked though, so should I create a new one?

**Comment by viceice** [comment]
nope:
- https://github.com/renovatebot/docker-sidecar/pull/15

**Comment by viceice** [comment]
yes, please reopen /reuse the existing pr. I also added a comment the the parent issue

**Pull request merged**
