### PR TITLE
feat(php): use prebuild binaries

### LINKED ISSUE #9: Use new php-prebuild

### PR DESCRIPTION
**Pull request by viceice**
Use our prebuild php binaries.

closes #9

### CODE REVIEW

**Comment by viceice** [comment]
Should we backport this to `renovatebot/docker-*` images ?

**Comment by rarkins** [comment]
> Should we backport this to `renovatebot/docker-*` images ?

Will it take long? If so then maybe next time the ubuntu base image changes?

**Comment by viceice** [comment]
I think that would be fast when it's working. There seem to be some extension issues which I need to investigate and fix first

**Review by rarkins — APPROVED** [review]

**Comment by viceice** [comment]
image


needs another fix for bionic 😕 Will do that later

**Pull request merged**
