### PR TITLE
chore: enable Renovate on helm bats files

### LINKED ISSUE #326: [TESTS] Make Helm version in bats test renovatable
Currently the bats tests for the helm tool are hardcoded and will not be versioned by Renovate.
We should enable all version in the bats tests to be automatically versioned by Renovate.

This probably requires a custom regex manager in the containerbase/.github repository.

Outcome of #300

### PR DESCRIPTION
**Pull request by Chumper**
Makes the helm bats tests versioned by Renovate

Closes #326

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
No longer defined as local?

**Comment by Chumper** [comment]
> No longer defined as local?

I would like to keep local but I haven't looked into the regex expression if that is supported.

**Comment by viceice** [comment]
Simply define as empty local and assign after? 🤗

**Comment by Chumper** [comment]
Some solutions are too simple. Thanks @viceice

**Review by viceice — APPROVED** [review]

**Pull request merged**
