### PR TITLE
test: add erlang v25 test

### PR DESCRIPTION
**Pull request by rarkins**
- blocked by #518

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
something seems to be wrong with v25

**Comment by viceice** [comment]
Elixir not yet compatible with erlang v25 https://hexdocs.pm/elixir/1.13.4/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

**Comment by viceice** [comment]
elixir v1.14 will support erlang v25 and will probably released nex 2 weeks

**Comment by Blond11516** [comment]
Elixir 1.14.0 has been released with support for Erlang 25. However, the format of assets in the github release has changed and is not longer compatible with the url used by `install-tool`: https://github.com/elixir-lang/elixir/releases/tag/v1.14.0

I suggest downloading releases from Hex instead, as does the [asdf elixir plugin](https://github.com/asdf-vm/asdf-elixir/blob/d08f506b72faddff571b819f586219295bf89d99/bin/install#L151). You can see the full list of versions available on Hex [here](https://repo.hex.pm/builds/elixir/builds.txt)

**Comment by viceice** [comment]
> Elixir 1.14.0 has been released with support for Erlang 25. However, the format of assets in the github release has changed and is no longer compatible with the url used by `install-tool`: https://github.com/elixir-lang/elixir/releases/tag/v1.14.0
> 
> I suggest downloading releases from Hex instead, as does the [asdf elixir plugin](https://github.com/asdf-vm/asdf-elixir/blob/d08f506b72faddff571b819f586219295bf89d99/bin/install#L151). You can see the full list of versions available on Hex [here](https://repo.hex.pm/builds/elixir/builds.txt)

Doesn't work for older releases, so did another workaround

**Review by viceice — APPROVED** [review]

**Pull request merged**
