### PR TITLE
feat(node): allow runtime install

### LINKED ISSUE #217: node: runtime install
`node` (tricky, to not interferre with renovate required node)

### PR DESCRIPTION
**Pull request by viceice**
- closes #217

### CODE REVIEW

**Comment by rarkins** [comment]
Do we need to purge any node installs (e.g. npm, pnpm, yarn) if we change node version?

**Comment by viceice** [comment]
> Do we need to purge any node installs (e.g. npm, pnpm, yarn) if we change node version?

I don't think so. Why should we need to purge?

**Comment by rarkins** [comment]
Might any of them build/install differently based on the version of node? I guess I'm thinking about re2 and similar

**Comment by viceice** [comment]
I've never seen that behavior on package managers, but i can add some more tests to verify

**Comment by rarkins** [comment]
We'd need it later for Eg new python means purging any pop or poetry?

**Comment by viceice** [comment]
Maybe, let's defer it, until we have something to test against.

**Pull request merged**
